require("plugins.depedencies")
require("plugins.lsp")
require("plugins.ui")
require("plugins.exploring")
require("plugins.editing")
require("plugins.treesitter")
require("plugins.ai")
require("plugins.scripts")
